// <auto-generated />
namespace MC.Internal.DevOps.MCDataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ProjTweaks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProjTweaks));
        
        string IMigrationMetadata.Id
        {
            get { return "201706012101349_ProjTweaks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
